version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.5.3

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - browser-tools/install-chrome
      - run:
          name: Run Tests
          command: mvn clean test
      - store_artifacts:
          path: target/reports
          destination: test-result
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          command: echo 'Running build step'

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build